import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./components/Header";
import { AuthProvider } from './context/AuthContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="login-page">
        <AuthProvider>
        <Header />
        <div className='container mt-3'>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
